openapi: 3.0.0
info:
  title: Sample API
  version: '1.0'
servers:
  - url: 'http://localhost:3000/v1'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
  schemas:
    PaginationResponse:
      type: object
      properties:
        countPerPage:
          type: number
        currentPageIndex:
          type: number
        totalPage:
          type: number
        totalCount:
          type: number
  parameters:
    CountPerPage:
      name: countPerPage
      in: query
      required: true
      description: The record count per page.
      schema:
        type: number
    PageIndex:
      name: pageIndex
      in: query
      required: true
      description: Current page index.
      schema:
        type: number
tags:
  - name: SampleArticle
    description: SampleArticle API
paths:
  /sampleArticles:
    get:
      description: Get sample artilces.
      tags:
        - SampleArticle
      parameters:
        - $ref: '#/components/parameters/CountPerPage'
        - $ref: '#/components/parameters/PageIndex'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginationResponse'
                  - properties:
                      records:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: number
                            title:
                              type: string
                            content:
                              type: string
                            createdAt:
                              type: string
                              format: date-time
                            updatedAt:
                              type: string
                              format: date-time
  /admin/sampleArticles:
    post:
      description: Add new sample article
      tags:
        - SampleArticle
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: title
                content:
                  type: string
                  description: content
                  minimum: 5
              required:
                - title
                - content
      responses:
        '201':
          description: created
  '/admin/sampleArticles/{articleId}':
    delete:
      security:
        - basicAuth: []
      description: Delete the sample article.
      tags:
        - SampleArticle
      parameters:
        - in: path
          name: articleId
          description: article id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: success.
    put:
      security:
        - basicAuth: []
      description: Edit the sample article.
      tags:
        - SampleArticle
      parameters:
        - in: path
          name: articleId
          description: article id
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: title
                content:
                  type: string
                  description: content
                  minimum: 5
      responses:
        '200':
          description: success.
